<a href="https://colab.research.google.com/github/Hirak-Pandya/Loan-Prediction-using-different-algos/blob/main/Loan_Prediction_using_different_algos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [306]:
from __future__ import print_function
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from google.colab import files
import pandas_profiling

In [307]:
train_data = pd.read_excel('Train-Data.xlsx')
test_data = pd.read_excel('Test-Data.xlsx')

In [308]:
#pandas_profiling.ProfileReport(train_data)

In [309]:
list(train_data)
['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']
# Print the 10 records of the training dataset
train_data.head(10)

Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0  LP001002   Male      No  ...            1.0         Urban           Y
1  LP001003   Male     Yes  ...            1.0         Rural           N
2  LP001005   Male     Yes  ...            1.0         Urban           Y
3  LP001006   Male     Yes  ...            1.0         Urban           Y
4  LP001008   Male      No  ...            1.0         Urban           Y
5  LP001011   Male     Yes  ...            1.0         Urban           Y
6  LP001013   Male     Yes  ...            1.0         Urban           Y
7  LP001014   Male     Yes  ...            0.0     Semiurban           N
8  LP001018   Male     Yes  ...            1.0         Urban           Y
9  LP001020   Male     Yes  ...            1.0     Semiurban           N

[10 rows x 13 columns]

In [310]:
train_data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [311]:
train_data.describe()

ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
count       614.000000         614.000000  ...         600.00000      564.000000
mean       5403.459283        1621.245798  ...         342.00000        0.842199
std        6109.041673        2926.248369  ...          65.12041        0.364878
min         150.000000           0.000000  ...          12.00000        0.000000
25%        2877.500000           0.000000  ...         360.00000        1.000000
50%        3812.500000        1188.500000  ...         360.00000        1.000000
75%        5795.000000        2297.250000  ...         360.00000        1.000000
max       81000.000000       41667.000000  ...         480.00000        1.000000

[8 rows x 5 columns]

In [312]:
train_data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [313]:
train_data.fillna(train_data.mean(), inplace=True)
train_data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [314]:
train_data.Gender.fillna(train_data.Gender.mode()[0], inplace=True)
train_data.Married.fillna(train_data.Married.mode()[0], inplace=True)
train_data.Dependents.fillna(train_data.Dependents.mode()[0], inplace=True)
train_data.Self_Employed.fillna(train_data.Self_Employed.mode()[0], inplace=True)
train_data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [315]:
test_data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [316]:
test_data.fillna(test_data.mean(), inplace=True)
test_data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
dtype: int64

In [317]:
test_data.Gender.fillna(test_data.Gender.mode()[0], inplace=True)
test_data.Dependents.fillna(test_data.Dependents.mode()[0], inplace=True)
test_data.Self_Employed.fillna(test_data.Self_Employed.mode()[0], inplace=True)
test_data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [318]:
train_data.Loan_Amount_Term=np.log(train_data.Loan_Amount_Term)

In [319]:
# Remove Loan_ID variable as it is Irrelevant
train_data = train_data.drop('Loan_ID', axis=1)
test_data = test_data.drop('Loan_ID', axis=1)

In [320]:
# Create target variable
a = train_data.drop('Loan_Status',axis=1)
b = train_data.Loan_Status
train_data.head(10)

Gender Married Dependents  ... Credit_History Property_Area  Loan_Status
0   Male      No          0  ...            1.0         Urban            Y
1   Male     Yes          1  ...            1.0         Rural            N
2   Male     Yes          0  ...            1.0         Urban            Y
3   Male     Yes          0  ...            1.0         Urban            Y
4   Male      No          0  ...            1.0         Urban            Y
5   Male     Yes          2  ...            1.0         Urban            Y
6   Male     Yes          0  ...            1.0         Urban            Y
7   Male     Yes         3+  ...            0.0     Semiurban            N
8   Male     Yes          2  ...            1.0         Urban            Y
9   Male     Yes          1  ...            1.0     Semiurban            N

[10 rows x 12 columns]

In [321]:
print(a)

     Gender Married Dependents  ... Loan_Amount_Term Credit_History  Property_Area
0      Male      No          0  ...         5.886104            1.0          Urban
1      Male     Yes          1  ...         5.886104            1.0          Rural
2      Male     Yes          0  ...         5.886104            1.0          Urban
3      Male     Yes          0  ...         5.886104            1.0          Urban
4      Male      No          0  ...         5.886104            1.0          Urban
..      ...     ...        ...  ...              ...            ...            ...
609  Female      No          0  ...         5.886104            1.0          Rural
610    Male     Yes         3+  ...         5.192957            1.0          Rural
611    Male     Yes          1  ...         5.886104            1.0          Urban
612    Male     Yes          2  ...         5.886104            1.0          Urban
613  Female      No          0  ...         5.886104            0.0      Semiurban

[61

In [322]:
print(b)

0      Y
1      N
2      Y
3      Y
4      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 614, dtype: object


In [323]:
a = pd.get_dummies(a) 
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)

In [324]:
a.head(10)

ApplicantIncome  ...  Property_Area_Urban
0             5849  ...                    1
1             4583  ...                    0
2             3000  ...                    1
3             2583  ...                    1
4             6000  ...                    1
5             5417  ...                    1
6             2333  ...                    1
7             3036  ...                    0
8             4006  ...                    1
9            12841  ...                    0

[10 rows x 20 columns]

In [325]:
# Split train data for cross validation
a_train, a_cv, b_train, b_cv = train_test_split(a, b, test_size=0.2)
print(a_train)
print(a_cv)

     ApplicantIncome  ...  Property_Area_Urban
176             2045  ...                    0
18              4887  ...                    0
522             5677  ...                    0
328             4333  ...                    1
326             4917  ...                    0
..               ...  ...                  ...
612             7583  ...                    1
559             4180  ...                    0
79              3333  ...                    0
97              1977  ...                    0
366             2500  ...                    0

[491 rows x 20 columns]
     ApplicantIncome  ...  Property_Area_Urban
513             2130  ...                    0
524             4680  ...                    0
206             3244  ...                    1
231             3716  ...                    0
461             7740  ...                    1
..               ...  ...                  ...
243             6250  ...                    0
236             5746  ...          

In [326]:
b_cv.head(10)

513    N
524    N
206    Y
231    Y
461    Y
410    N
518    N
389    Y
162    N
422    Y
Name: Loan_Status, dtype: object

**Logistic** **Regression**

In [327]:
# Fit model
log_model = LogisticRegression()  
log_model.fit(a_train, b_train) 

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [328]:
# Predict values for cv data
pred_cv = log_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv)) # 75.60 %
matrix = confusion_matrix(b_cv, pred_cv)
print(matrix)

0.7560975609756098
[[18 28]
 [ 2 75]]


 **Decision Tree Algorithm**

In [329]:
# Fit model
dt_model = tree.DecisionTreeClassifier(criterion='gini')
dt_model.fit(a_train, b_train)

DecisionTreeClassifier()

In [330]:
# Predict values for cv data
pred_cv1 = dt_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv1)) # 66.66 %
matrix1 = confusion_matrix(b_cv, pred_cv1)
print(matrix1)

0.6178861788617886
[[21 25]
 [22 55]]


**RANDOM FOREST ALGORITHM**

In [331]:
# Fit model
rf_model = RandomForestClassifier()
rf_model.fit(a_train, b_train)

RandomForestClassifier()

In [332]:
# Predict values for cv data
pred_cv2 = rf_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv2)) # 74.79 %
matrix2 = confusion_matrix(b_cv, pred_cv2)
print(matrix2)

0.7398373983739838
[[19 27]
 [ 5 72]]


**SUPPORT VECTOR MACHINE (SVM) ALGORITHM**

In [333]:
# Fit model 
svm_model = svm.SVC()
svm_model.fit(a_train, b_train)

SVC()

In [334]:
# Predict values for cv data
pred_cv3 = svm_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv3)) # 62.60 %
matrix3 = confusion_matrix(b_cv, pred_cv3)
print(matrix3)

0.6260162601626016
[[ 0 46]
 [ 0 77]]


**NAIVE BAYES ALGORITHM**

In [335]:
# Fit model 
nb_model = GaussianNB()
nb_model.fit(a_train, b_train)

GaussianNB()

In [336]:
# Predict values for cv data
pred_cv4 = nb_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv4)) # 76.42 %
matrix4 = confusion_matrix(b_cv, pred_cv4)
print(matrix4)

0.7398373983739838
[[17 29]
 [ 3 74]]


**K-NEAREST NEIGHBOR(kNN) ALGORITHM**

In [337]:
# Fit model
kNN_model = KNeighborsClassifier()
kNN_model.fit(a_train, b_train)

KNeighborsClassifier()

In [338]:
# Predict values for cv data
pred_cv5 = kNN_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv5)) # 61.78 %
matrix5 = confusion_matrix(b_cv, pred_cv5)
print(matrix5)

0.5609756097560976
[[ 5 41]
 [13 64]]


**GRADIENT BOOSTING MACHINE ALGORITHM**

In [339]:
# Fit model
gbm_model = GradientBoostingClassifier()
gbm_model.fit(a_train, b_train)

GradientBoostingClassifier()

In [340]:
# Predict values for cv data
pred_cv6 = gbm_model.predict(a_cv)

# Evaluate accuracy of model
print(accuracy_score(b_cv, pred_cv6)) # 73.98 %
matrix6 = confusion_matrix(b_cv, pred_cv6)
print(matrix6)

0.7560975609756098
[[18 28]
 [ 2 75]]


In [341]:
test_data

ApplicantIncome  ...  Property_Area_Urban
0               5720  ...                    1
1               3076  ...                    1
2               5000  ...                    1
3               2340  ...                    1
4               3276  ...                    1
..               ...  ...                  ...
362             4009  ...                    1
363             4158  ...                    1
364             3250  ...                    0
365             5000  ...                    0
366             9200  ...                    0

[367 rows x 20 columns]

In [342]:
# Predict values using test data (Logistic Regression)
pred_test = dt_model.predict(test_data)

# Write test results in csv file

pred_test

array(['Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N',
       'N', 'N', 'N', 'N', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'Y',
       'Y', 'N', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y',
       'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y',
       'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'N',
       'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'N', 'N',
       'N', 'N', 'N', 'N', 'Y', 'Y', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y',
       'Y', 'N', 'N', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N',
       'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N', 'Y', 'N',
       'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y

In [343]:
len(pred_test)

367

In [344]:
loan_predictions=pd.DataFrame(pred_test, columns=['Predictions']).to_excel("LoanStatus_Prediction.xlsx")